# Generated by Django 2.2.5 on 2019-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_squarefootlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarefootlayout',
            name='fill_cols',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='squarefootlayout',
            name='fill_rows',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
