# Generated by Django 2.2.5 on 2019-09-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190925_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squarefootlayout',
            name='fill_cols',
        ),
        migrations.RemoveField(
            model_name='squarefootlayout',
            name='fill_rows',
        ),
        migrations.AddField(
            model_name='squarefootlayout',
            name='fill',
            field=models.CharField(default='all', max_length=500),
        ),
    ]
