# Generated by Django 2.2.5 on 2019-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190925_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='layouts',
            field=models.ManyToManyField(related_name='plants', to='backend.SquareFootLayout'),
        ),
    ]
