# Generated by Django 2.2.5 on 2019-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_plant_layouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='enemies',
            field=models.ManyToManyField(related_name='_plant_enemies_+', to='backend.Plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='friends',
            field=models.ManyToManyField(related_name='_plant_friends_+', to='backend.Plant'),
        ),
    ]
