# Generated by Django 2.2.5 on 2019-09-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190925_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='enemies',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='friends',
        ),
        migrations.AddField(
            model_name='plant',
            name='bad_neighbors',
            field=models.ManyToManyField(related_name='_plant_bad_neighbors_+', to='backend.Plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='good_neighbors',
            field=models.ManyToManyField(related_name='_plant_good_neighbors_+', to='backend.Plant'),
        ),
    ]
