# Generated by Django 2.2.5 on 2019-09-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190925_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='bad_neighbors',
            field=models.ManyToManyField(blank=True, related_name='_plant_bad_neighbors_+', to='backend.Plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='good_neighbors',
            field=models.ManyToManyField(blank=True, related_name='_plant_good_neighbors_+', to='backend.Plant'),
        ),
    ]
