# Generated by Django 2.2.5 on 2019-10-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_plant_name_plural'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name']},
        ),
    ]
